In [1]:
import sys
import os
import gc
# Add the parent directory to the system path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), os.pardir)))


In [2]:
from ZeroHelperFunctions.JamesWeb import JamesWeb
from ZeroHelperFunctions.SaveLoadModels import save_model, load_model
from Networks.networks import FullyConnectedNet

In [3]:
NUM_DIMENSIONS = 28*28
sample_mnist_model = FullyConnectedNet(input_dim=NUM_DIMENSIONS,
                    layer1_dim=NUM_DIMENSIONS * 10,
                    layer2_dim=NUM_DIMENSIONS * 5,
                    layer3_dim=11*10,
                    num_classes=11)

sample_fk_mnist_model = FullyConnectedNet(input_dim=NUM_DIMENSIONS,
                    layer1_dim=NUM_DIMENSIONS * 15,
                    layer2_dim=NUM_DIMENSIONS * 7,
                    layer3_dim=11*10,
                    num_classes=11)

In [4]:
import torch

mnist_model = load_model(sample_mnist_model,
                                 model_save_path="models/mnist_full.pth", 
                                 device="cuda" if torch.cuda.is_available() else "cpu")
fashion_mnist_model = load_model(sample_fk_mnist_model,
                                 model_save_path="models/fashion_mnist_full.pth", 
                                 device="cuda" if torch.cuda.is_available() else "cpu")
k_mnist_model = load_model(sample_fk_mnist_model,
                                 model_save_path="models/k_mnist_full.pth", 
                                 device="cuda" if torch.cuda.is_available() else "cpu")

from MnistHelperFunctions.get_standard_data import preprocessed_mnist, preprocessed_fashion_mnist, preprocessed_k_mnist
mnist_train_data, mnist_test_data = preprocessed_mnist()
fashion_mnist_train_data, fashion_mnist_test_data = preprocessed_fashion_mnist()
k_mnist_train_data, k_mnist_test_data = preprocessed_k_mnist()



Data format: 
--------------------------------
type(train_data.data[0]) -> <class 'torch.Tensor'>
train_data.data[0].dtype -> torch.float32

type(train_data.targets) -> <class 'torch.Tensor'>
train_data.targets.dtype -> torch.int64


Access Data by indexing
--------------------------------
train_data[0] -> (torch.Size([28, 28]), torch.Size([]))


max and min values of train_data.data:
--------------------------------
	[(tensor(0.), tensor(1.))]





Data format: 
--------------------------------
type(train_data.data[0]) -> <class 'torch.Tensor'>
train_data.data[0].dtype -> torch.float32

type(train_data.targets) -> <class 'torch.Tensor'>
train_data.targets.dtype -> torch.int64


Access Data by indexing
--------------------------------
train_data[0] -> (torch.Size([28, 28]), torch.Size([]))


max and min values of train_data.data:
--------------------------------
	[(tensor(0.), tensor(1.))]





Data format: 
--------------------------------
type(train_data.data[0]) -> <class 'torch.T

In [5]:
james = JamesWeb(device="cuda" if torch.cuda.is_available() else "cpu")

In [6]:
james.add_model(mnist_model,
                "mnist")
mnist_test_data.targets = james.convert_labels(mnist_test_data.targets,
                                               "mnist")
james.add_model(fashion_mnist_model,
                "fashion_mnist")
fashion_mnist_test_data.targets = james.convert_labels(fashion_mnist_test_data.targets,
                                                       "fashion_mnist")

mnist is in the list at index 0.
fashion_mnist is in the list at index 1.


In [7]:
james.model_names

['mnist', 'fashion_mnist']

In [8]:
james.predictions(mnist_test_data.data[:20]).transpose(0, 1), mnist_test_data.targets[:20].transpose(0, 1)

(tensor([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [7, 2, 1, 0, 4, 1, 4, 9, 2, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4]]),
 tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4]]))

In [11]:
james.predictions(fashion_mnist_test_data.data[:20]).transpose(0, 1), fashion_mnist_test_data.targets[:20].transpose(0, 1)

(tensor([[ 0,  0,  1,  1,  0,  0,  0,  1,  0,  1,  0,  0,  1,  1,  1,  0,  0,  0,
           1,  1],
         [ 2, 10,  1,  6, 10,  0, 10,  6,  4,  7, 10,  2,  7,  8,  6,  3, 10, 10,
           0,  6]]),
 tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [9, 2, 1, 1, 6, 1, 4, 6, 5, 7, 4, 5, 7, 3, 4, 1, 2, 4, 8, 0]]))